/// <reference types ="cypress" />

import { ColorTextStrong, ColorTextStandard, ColorMagenta01, SmallRadius, Separator, ColorGray10, ColorGray11, SeparatorChrome} from "./variables";
beforeEach (() => {
    cy.visit('https://www.millenniumbm.pl/serwisy-i-narzedzia/informacje-dla-akcjonariuszy');
    cy.viewport(1920, 1080);
    cy.get("div#cookie-m-wrapper-n div.cookies-m-buttons a#allow-cookies-m-btn").click();
    
})

describe("SHAREHOLDERS_SEARCH_2023 - Informacje dla akcjonariuszy", () => {
    const shareholdersSearchId = "div#p_p_id_com_liferay_journal_content_web_portlet_JournalContentPortlet_INSTANCE_KfNFFOz93fWb_";
    it("Sprawdzenie połozenia komponentu", () => {
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search`).should("have.css", "display", "flex");
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search`).should("have.css", "justify-content", "center");
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search`).should("have.css", "width", "1920px");
    });
    it("Sprawdzenie ustawienia komponentu", () => {
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container`).should("have.css", "display", "flex");    
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container`).should("have.css", "flex-direction", "column");    
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container`).should("have.css", "align-items", "center");    
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container`).should("have.css", "justify-content", "center");    
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container`).should("have.css", "width", "1660px");    
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container`).should("have.css", "max-width", "1660px");    
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container`).should("have.css", "padding-left", "30px");    
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container`).should("have.css", "padding-right", "30px");    
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container`).should("have.css", "margin", "0px");    
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container`).should("have.css", "box-sizing", "border-box");    
    });
    it("Sprawdzenie kontenera headera", () => {
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__header`).should("have.css", "box-sizing", "border-box"); 
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__header`).should("have.css", "display", "flex"); 
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__header`).should("have.css", "flex-direction", "row"); 
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__header`).should("have.css", "width", "1600px"); 
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__header`).should("have.css", "text-align", "left"); 
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__header`).should("have.css", "transition", "0.3s"); 
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__header`).should("have.css", "margin", "0px"); 
    })
    it("Sprawdzenie treści headera", () => {
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__header h2`).should("have.css", "box-sizing", "border-box");
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__header h2`).should("have.css", "font-weight", "700");
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__header h2`).should("have.css", "color", `${ColorTextStrong}`);
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__header h2`).should("have.css", "text-transform", "none");
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__header h2`).should("have.css", "font-size", "30px");
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__header h2`).should("have.css", "line-height", "36px");
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__header h2`).should("have.css", "overflow-wrap", "break-word");
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__header h2`).should("have.css", "margin", "0px");
    })
    it("Sprawdzenie kontenera opisu", () => {
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__paragraph`).should("have.css", "box-sizing", "border-box");
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__paragraph`).should("have.css", "width", "1600px");
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__paragraph`).should("have.css", "text-align", "left");
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__paragraph`).should("have.css", "font-weight", "400");
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__paragraph`).should("have.css", "text-decoration").should("be.oneOf", ["none", "none solid rgb(115, 115, 115)", `${ColorTextStandard}`]);
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__paragraph`).should("have.css", "color", `${ColorTextStandard}`);
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__paragraph`).should("have.css", "font-size", "18px");
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__paragraph`).should("have.css", "line-height", "24px"); 
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__paragraph`).should("have.css", "margin-top", "16px");
    });
    it("Sprawdzenie opisu", () => {
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__paragraph p`).should("have.css", "box-sizing", "border-box");
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__paragraph p`).should("have.css", "color", `${ColorGray11}`);
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__paragraph p`).should("have.css", "margin", "0px");
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__paragraph p`).should("have.css", "font-size", "16px");
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__paragraph p`).should("have.css", "line-height", "22px");
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__paragraph p`).should("have.css", "font-weight", "400");
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__paragraph p`).should("have.css", "text-decoration").should("be.oneOf", ["none", "none solid rgb(46, 46, 46)", `${ColorTextStrong}`]);
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__paragraph p`).should("have.css", "overflow-wrap", "break-word");
    });
    it("Sprawdzenie umiejscowienia wyszukiwarki", () => {
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__input`).should("have.css", "width").should("be.oneOf", ["600px", "100%"]);
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__input`).should("have.css", "max-width", "600px");
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__input`).should("have.css", "margin-top", "40px");
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__input`).should("have.css", "margin-bottom", "48px");
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__input`).should("have.css", "box-sizing", "border-box");
    });
    it("Sprawdzenie styli wyszukiwarki", () => {
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__input div.mds.bm-search-input`).should("have.css", "box-sizing", "border-box");
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__input div.mds.bm-search-input`).should("have.css", "position", "relative");
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__input div.mds.bm-search-input`).should("have.css", "color", `${ColorGray10}`);
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__input div.mds.bm-search-input input.bm-search-input__input`).should("have.css", "padding", "0px 16px 0px 56px");
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__input div.mds.bm-search-input input.bm-search-input__input`).should("have.css", "text-overflow", "ellipsis");
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__input div.mds.bm-search-input input.bm-search-input__input`).should("have.css", "white-space").should("be.oneOf", ["nowrap", "no-wrap"]);
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__input div.mds.bm-search-input input.bm-search-input__input`).should("have.css", "width", "600px");
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__input div.mds.bm-search-input input.bm-search-input__input`).should("have.css", "height", "51px");
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__input div.mds.bm-search-input input.bm-search-input__input`).should("have.css", "color", "rgb(115, 115, 115)");
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__input div.mds.bm-search-input input.bm-search-input__input`).should("have.css", "caret-color", `${ColorMagenta01}`);
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__input div.mds.bm-search-input input.bm-search-input__input`).should("have.css", "border").should("be.oneOf", ["1.33333px solid rgb(211, 211, 211)", "1px solid rgb(211, 211, 211)"]);
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__input div.mds.bm-search-input input.bm-search-input__input`).should("have.css", "border-radius", "26px");
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__input div.mds.bm-search-input input.bm-search-input__input`).should("have.css", "background-color", "rgb(255, 255, 255)");
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__input div.mds.bm-search-input input.bm-search-input__input`).should("have.css", "background-image").should("be.oneOf", [`url("data:image/svg+xml,%3c?xml%20version=%271.0%27%20encoding=%27UTF-8%27?%3e%3csvg%20id=%27d%27%20xmlns=%27http://www.w3.org/2000/svg%27%20width=%2724%27%20height=%2724%27%20xmlns:xlink=%27http://www.w3.org/1999/xlink%27%20viewBox=%270%200%2024%2024%27%3e%3cdefs%3e%3cclipPath%20id=%27e%27%3e%3crect%20id=%27f%27%20width=%2724%27%20height=%2724%27%20fill=%27none%27/%3e%3c/clipPath%3e%3c/defs%3e%3cg%20clip-path=%27url(%23e)%27%3e%3cpath%20d=%27M21.707,20.293l-3.6819-3.6819c1.2327-1.5402,1.9749-3.4893,1.9749-5.6111,0-4.9629-4.0371-9-9-9S2,6.0371,2,11s4.0376,9,9,9c2.1218,0,4.0709-.7422,5.6111-1.9749l3.6819,3.6819c.1953,.1953,.4512,.293,.707,.293s.5117-.0977,.707-.293c.3906-.3906,.3906-1.0234,0-1.4141Zm-10.707-2.293c-3.8599,0-7-3.1406-7-7s3.1401-7,7-7,7,3.1406,7,7-3.1406,7-7,7Z%27%20fill=%27%232e2e2e%27/%3e%3c/g%3e%3c/svg%3e")`, `url("data:image/svg+xml,%3c?xml%20version='1.0'%20encoding='UTF-8'?%3e%3csvg%20id='d'%20xmlns='http://www.w3.org/2000/svg'%20width='24'%20height='24'%20xmlns:xlink='http://www.w3.org/1999/xlink'%20viewBox='0%200%2024%2024'%3e%3cdefs%3e%3cclipPath%20id='e'%3e%3crect%20id='f'%20width='24'%20height='24'%20fill='none'/%3e%3c/clipPath%3e%3c/defs%3e%3cg%20clip-path='url(%23e)'%3e%3cpath%20d='M21.707,20.293l-3.6819-3.6819c1.2327-1.5402,1.9749-3.4893,1.9749-5.6111,0-4.9629-4.0371-9-9-9S2,6.0371,2,11s4.0376,9,9,9c2.1218,0,4.0709-.7422,5.6111-1.9749l3.6819,3.6819c.1953,.1953,.4512,.293,.707,.293s.5117-.0977,.707-.293c.3906-.3906,.3906-1.0234,0-1.4141Zm-10.707-2.293c-3.8599,0-7-3.1406-7-7s3.1401-7,7-7,7,3.1406,7,7-3.1406,7-7,7Z'%20fill='%232e2e2e'/%3e%3c/g%3e%3c/svg%3e")`]);
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__input div.mds.bm-search-input input.bm-search-input__input`).should("have.css", "background-repeat", "no-repeat");
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__input div.mds.bm-search-input input.bm-search-input__input`).should("have.css", "background-position").should("be.oneOf", ["16px 16px", "16px 50%"]);
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__input div.mds.bm-search-input input.bm-search-input__input`).should("have.css", "box-shadow", "none");
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__input div.mds.bm-search-input button.bm-search-input__clear-button`).should("have.attr", "tabindex", "-1");
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__input div.mds.bm-search-input button.bm-search-input__clear-button`).should("have.css", "display", "none");
        // cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__input div.mds.bm-search-input input.bm-search-input__input`).type("test {enter}", {delay: 500});//wpisanie czego kolwiek żeby pojawił się button X
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__input div.mds.bm-search-input button.bm-search-input__clear-button`).invoke('css', 'display', 'block')
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__input div.mds.bm-search-input button.bm-search-input__clear-button`).should("be.visible");

        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__input div.mds.bm-search-input input.bm-search-input__input`).should("have.css", "position", "static");
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__input div.mds.bm-search-input input.bm-search-input__input`).should("have.css", "border").should("be.oneOf", ["none", "1.33333px solid rgb(211, 211, 211)", "1px solid rgb(211, 211, 211)"]);
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__input div.mds.bm-search-input input.bm-search-input__input`).should("have.css", "top"). should("be.oneOf", ["0px", "auto"]);
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__input div.mds.bm-search-input input.bm-search-input__input`).should("have.css", "right").should("be.oneOf", ["0px", "auto"]);
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__input div.mds.bm-search-input input.bm-search-input__input`).should("have.css", "height", "51px");
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__input div.mds.bm-search-input input.bm-search-input__input`).should("have.css", "width", "600px");
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__input div.mds.bm-search-input input.bm-search-input__input`).should("have.css", "border-radius", "26px");
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__input div.mds.bm-search-input input.bm-search-input__input`).should("have.css", "background-color", "rgb(255, 255, 255)");
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__input div.mds.bm-search-input input.bm-search-input__input`).should("have.css", "background-image").should("be.oneOf", [`url("data:image/svg+xml,%3c?xml%20version=%271.0%27%20encoding=%27UTF-8%27?%3e%3csvg%20id=%27d%27%20xmlns=%27http://www.w3.org/2000/svg%27%20width=%2724%27%20height=%2724%27%20xmlns:xlink=%27http://www.w3.org/1999/xlink%27%20viewBox=%270%200%2024%2024%27%3e%3cdefs%3e%3cclipPath%20id=%27e%27%3e%3crect%20id=%27f%27%20width=%2724%27%20height=%2724%27%20fill=%27none%27/%3e%3c/clipPath%3e%3c/defs%3e%3cg%20clip-path=%27url(%23e)%27%3e%3cpath%20d=%27M21.707,20.293l-3.6819-3.6819c1.2327-1.5402,1.9749-3.4893,1.9749-5.6111,0-4.9629-4.0371-9-9-9S2,6.0371,2,11s4.0376,9,9,9c2.1218,0,4.0709-.7422,5.6111-1.9749l3.6819,3.6819c.1953,.1953,.4512,.293,.707,.293s.5117-.0977,.707-.293c.3906-.3906,.3906-1.0234,0-1.4141Zm-10.707-2.293c-3.8599,0-7-3.1406-7-7s3.1401-7,7-7,7,3.1406,7,7-3.1406,7-7,7Z%27%20fill=%27%232e2e2e%27/%3e%3c/g%3e%3c/svg%3e")`, `url("data:image/svg+xml,%3c?xml%20version='1.0'%20encoding='UTF-8'?%3e%3csvg%20id='d'%20xmlns='http://www.w3.org/2000/svg'%20width='24'%20height='24'%20xmlns:xlink='http://www.w3.org/1999/xlink'%20viewBox='0%200%2024%2024'%3e%3cdefs%3e%3cclipPath%20id='e'%3e%3crect%20id='f'%20width='24'%20height='24'%20fill='none'/%3e%3c/clipPath%3e%3c/defs%3e%3cg%20clip-path='url(%23e)'%3e%3cpath%20d='M21.707,20.293l-3.6819-3.6819c1.2327-1.5402,1.9749-3.4893,1.9749-5.6111,0-4.9629-4.0371-9-9-9S2,6.0371,2,11s4.0376,9,9,9c2.1218,0,4.0709-.7422,5.6111-1.9749l3.6819,3.6819c.1953,.1953,.4512,.293,.707,.293s.5117-.0977,.707-.293c.3906-.3906,.3906-1.0234,0-1.4141Zm-10.707-2.293c-3.8599,0-7-3.1406-7-7s3.1401-7,7-7,7,3.1406,7,7-3.1406,7-7,7Z'%20fill='%232e2e2e'/%3e%3c/g%3e%3c/svg%3e")`]);
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__input div.mds.bm-search-input input.bm-search-input__input`).should("have.css", "background-repeat", "no-repeat");
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__input div.mds.bm-search-input input.bm-search-input__input`).should("have.css", "background-position", "16px 50%");
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__input div.mds.bm-search-input input.bm-search-input__input `).should("have.css", "box-sizing", "border-box");
    })
    it("Sprawdzenie ustawienia kontenera - eventy", () => {
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__events`).should("have.css", "display", "flex");
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__events`).should("have.css", "flex-direction", "column");
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__events`).should("have.css", "align-items", "center");
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__events`).should("have.css", "justify-content", "center");
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__events`).should("have.css", "width", "1080px");
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__events`).should("have.css", "max-width", "1080px");
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__events`).should("have.css", "box-sizing", "border-box");
    });
    it("Sprawdzenie styli pierwszego elementu listy", () => {
        //header cały
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__events div.bm-events-search__event-header`).first().should("have.css", "box-sizing", "border-box"); 
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__events div.bm-events-search__event-header`).first().should("have.css", "display", "flex"); 
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__events div.bm-events-search__event-header`).first().should("have.css", "flex-direction", "row"); 
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__events div.bm-events-search__event-header`).first().should("have.css", "width", "1080px"); 
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__events div.bm-events-search__event-header`).first().should("have.css", "justify-content", "space-between"); 
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__events div.bm-events-search__event-header`).first().should("have.css", "align-items", "center"); 
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__events div.bm-events-search__event-header`).first().should("have.css", "font-family", "Roboto, sans-serif");
        // lewa strona headera
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__events div.bm-events-search__event-header label.bm-events-search__event-header-container`).first().should("have.css", "display", "flex"); 
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__events div.bm-events-search__event-header label.bm-events-search__event-header-container`).first().should("have.css", "flex-direction", "row"); 
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__events div.bm-events-search__event-header label.bm-events-search__event-header-container`).first().should("have.css", "flex-grow", "1"); 
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__events div.bm-events-search__event-header label.bm-events-search__event-header-container`).first().should("have.css", "align-items", "center"); 
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__events div.bm-events-search__event-header label.bm-events-search__event-header-container`).first().should("have.css", "font-size", "14px"); 
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__events div.bm-events-search__event-header label.bm-events-search__event-header-container`).first().should("have.css", "line-height", "20px"); 
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__events div.bm-events-search__event-header label.bm-events-search__event-header-container`).first().should("have.css", "font-weight", "400"); 
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__events div.bm-events-search__event-header label.bm-events-search__event-header-container`).first().should("have.css", "cursor", "pointer"); 
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__events div.bm-events-search__event-header label.bm-events-search__event-header-container`).first().should("have.css", "box-sizing", "border-box");
        //title and description
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__events div.bm-events-search__event-header label.bm-events-search__event-header-container div.bm-events-search__event-title-and-description`).first().should("have.css", "flex-grow", "1");
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__events div.bm-events-search__event-header label.bm-events-search__event-header-container div.bm-events-search__event-title-and-description h6`).first().should("have.css", "font-size", "16px");
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__events div.bm-events-search__event-header label.bm-events-search__event-header-container div.bm-events-search__event-title-and-description h6`).first().should("have.css", "line-height", "22px");
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__events div.bm-events-search__event-header label.bm-events-search__event-header-container div.bm-events-search__event-title-and-description h6`).first().should("have.css", "text-decoration", ).should("be.oneOf", ["none", `${ColorTextStrong}`, "none solid rgb(46, 46, 46)"]);
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__events div.bm-events-search__event-header label.bm-events-search__event-header-container div.bm-events-search__event-title-and-description h6`).first().should("have.css", "font-weight", "700");
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__events div.bm-events-search__event-header label.bm-events-search__event-header-container div.bm-events-search__event-title-and-description h6`).first().should("have.css", "color", `${ColorTextStrong}`);
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__events div.bm-events-search__event-header label.bm-events-search__event-header-container div.bm-events-search__event-title-and-description h6`).first().should("have.css", "margin-bottom", "8px");
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__events div.bm-events-search__event-header label.bm-events-search__event-header-container div.bm-events-search__event-title-and-description div`).first().should("have.css", "font-size", "14px");
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__events div.bm-events-search__event-header label.bm-events-search__event-header-container div.bm-events-search__event-title-and-description div`).first().should("have.css", "line-height", "20px");
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__events div.bm-events-search__event-header label.bm-events-search__event-header-container div.bm-events-search__event-title-and-description div`).first().should("have.css", "font-weight", "400");
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__events div.bm-events-search__event-header label.bm-events-search__event-header-container div.bm-events-search__event-title-and-description div`).first().should("have.css", "color", `${ColorGray11}`);
        //date
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__events div.bm-events-search__event-header label.bm-events-search__event-header-container div.bm-events-search__event-title-date`).first().should("have.css", "color", `${ColorGray11}`);
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__events div.bm-events-search__event-header label.bm-events-search__event-header-container div.bm-events-search__event-title-date`).first().should("have.css", "font-weight", "700");
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__events div.bm-events-search__event-header label.bm-events-search__event-header-container div.bm-events-search__event-title-date`).first().should("have.css", "font-size", "16px");
        //chevron
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__events div.bm-events-search__event-header label.bm-events-search__accordion-chevron`).first().should("have.css", "margin-left", "10px");
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__events div.bm-events-search__event-header label.bm-events-search__accordion-chevron`).first().should("have.css", "max-height", "25px");
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__events div.bm-events-search__event-header label.bm-events-search__accordion-chevron`).first().should("have.css", "transform").should("be.oneOf", ["rotate(180deg)", "matrix(-1, 0, 0, -1, 0, 0)"]);
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__events div.bm-events-search__event-header label.bm-events-search__accordion-chevron`).first().should("have.css", "transition").should("be.oneOf", ["all .2s ease-out", "0.2s ease-out"]);
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__events div.bm-events-search__event-header label.bm-events-search__accordion-chevron`).first().should("have.css", "box-sizing", "border-box");
        //chevron ikona
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__events div.bm-events-search__event-header label.bm-events-search__accordion-chevron i`).first().should("have.css", "appearance").should("be.oneOf", ["none", "rgba(0, 0, 0, 0) none repeat scroll 0% 0% / auto padding-box border-box"]);
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__events div.bm-events-search__event-header label.bm-events-search__accordion-chevron i`).first().should("have.css", "background").should("be.oneOf", ["none", "rgba(0, 0, 0, 0) none repeat scroll 0% 0% / auto padding-box border-box"]);;
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__events div.bm-events-search__event-header label.bm-events-search__accordion-chevron i`).first().should("have.css", "cursor", "pointer");
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__events div.bm-events-search__event-header label.bm-events-search__accordion-chevron i`).first().should("have.css", "display", "inline-block");
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__events div.bm-events-search__event-header label.bm-events-search__accordion-chevron i`).first().should("have.css", "position", "relative");
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__events div.bm-events-search__event-header label.bm-events-search__accordion-chevron i`).first().should("have.css", "text-align", "center");
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__events div.bm-events-search__event-header label.bm-events-search__accordion-chevron i`).first().should("have.css", "width", "24px");
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__events div.bm-events-search__event-header label.bm-events-search__accordion-chevron i`).first().should("have.css", "height", "24px");
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__events div.bm-events-search__event-header label.bm-events-search__accordion-chevron i`).first().should("have.css", "box-sizing", "border-box");
    })
    it("Sprawdzenie treści rozwiniętych - kontener", () => {
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__events div.bm-events-search__event-header label.bm-events-search__accordion-chevron`).first().click();
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__events div.bm-events-search__event div.bm-events-search__boxes`).first().should("have.css", "display", "flex");
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__events div.bm-events-search__event div.bm-events-search__boxes`).first().should("have.css", "height").should((height) => {
            // ensure the unit is in pixels
            expect(height).to.include('px')
            // get Number value and assert "381.15625px"
            expect(parseInt(height, 10)).to.be.within(424, 425);
          });
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__events div.bm-events-search__event div.bm-events-search__boxes`).first().should("have.css", "max-height", "10000px");
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__events div.bm-events-search__event div.bm-events-search__boxes`).first().should("have.css", "opacity", "1");
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__events div.bm-events-search__event div.bm-events-search__boxes`).first().should("have.css", "transition").should("be.oneOf", ["transition", "all. .6s ease-out ! important", "transition", "all. 0.6s ease-out ! important", "0.6s ease-out"]);
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__events div.bm-events-search__event div.bm-events-search__boxes`).first().should("have.css", "overflow", "hidden");
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__events div.bm-events-search__event div.bm-events-search__boxes`).first().should("have.css", "flex-direction", "row");
    })
    it("Sprawdzenie lewej strony - kontener", () => {
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__events div.bm-events-search__event div.bm-events-search__boxes div.bm-events-search__details-container`).first().should("have.css", "width", "636px");
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__events div.bm-events-search__event div.bm-events-search__boxes div.bm-events-search__details-container`).first().should("have.css", "margin", "10px 10px 0px 0px");
    });
    it("Sprawdzenie lewej strony - środek kontenera", () => {
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__events div.bm-events-search__event div.bm-events-search__boxes div.bm-events-search__details-container fieldset.mds.bm-box-outline.titled.bm-events-search__outline`).first().should("have.css", "padding-top", "16px");
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__events div.bm-events-search__event div.bm-events-search__boxes div.bm-events-search__details-container fieldset.mds.bm-box-outline.titled.bm-events-search__outline`).first().should("have.css", "box-sizing", "border-box");
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__events div.bm-events-search__event div.bm-events-search__boxes div.bm-events-search__details-container fieldset.mds.bm-box-outline.titled.bm-events-search__outline`).first().should("have.css", "display", "flex");
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__events div.bm-events-search__event div.bm-events-search__boxes div.bm-events-search__details-container fieldset.mds.bm-box-outline.titled.bm-events-search__outline`).first().should("have.css", "flex-direction", "column");
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__events div.bm-events-search__event div.bm-events-search__boxes div.bm-events-search__details-container fieldset.mds.bm-box-outline.titled.bm-events-search__outline`).first().should("have.css", "width", "636px");
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__events div.bm-events-search__event div.bm-events-search__boxes div.bm-events-search__details-container fieldset.mds.bm-box-outline.titled.bm-events-search__outline`).first().should("have.css", "max-width", "640px");
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__events div.bm-events-search__event div.bm-events-search__boxes div.bm-events-search__details-container fieldset.mds.bm-box-outline.titled.bm-events-search__outline`).first().should("have.css", "padding", "16px 32px 32px");
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__events div.bm-events-search__event div.bm-events-search__boxes div.bm-events-search__details-container fieldset.mds.bm-box-outline.titled.bm-events-search__outline`).first().should("have.css", "background").should("be.oneOf", ["rgb(255, 255, 255)", "rgb(255, 255, 255) none repeat scroll 0% 0% / auto padding-box border-box"]);
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__events div.bm-events-search__event div.bm-events-search__boxes div.bm-events-search__details-container fieldset.mds.bm-box-outline.titled.bm-events-search__outline`).first().should("have.css", "border").should("be.oneOf", ["1px solid rgb(211, 211, 211)", "1.33333px solid rgb(211, 211, 211)"]);
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__events div.bm-events-search__event div.bm-events-search__boxes div.bm-events-search__details-container fieldset.mds.bm-box-outline.titled.bm-events-search__outline`).first().should("have.css", "border-radius", "10px");
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__events div.bm-events-search__event div.bm-events-search__boxes div.bm-events-search__details-container fieldset.mds.bm-box-outline.titled.bm-events-search__outline`).first().should("have.css", "margin-top", "16px");
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__events div.bm-events-search__event div.bm-events-search__boxes div.bm-events-search__details-container fieldset.mds.bm-box-outline.titled.bm-events-search__outline`).first().should("have.css", "word-break", "break-word");
    })
    it("Sprawdzenie napisu szczegóły", () => {
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__events div.bm-events-search__event div.bm-events-search__boxes div.bm-events-search__details-container fieldset.mds.bm-box-outline.titled.bm-events-search__outline legend`).first().should("have.css", "text-transform", "uppercase");
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__events div.bm-events-search__event div.bm-events-search__boxes div.bm-events-search__details-container fieldset.mds.bm-box-outline.titled.bm-events-search__outline legend`).first().should("have.css", "padding-top", "3px");
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__events div.bm-events-search__event div.bm-events-search__boxes div.bm-events-search__details-container fieldset.mds.bm-box-outline.titled.bm-events-search__outline legend`).first().should("have.css", "padding-left", "5px");
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__events div.bm-events-search__event div.bm-events-search__boxes div.bm-events-search__details-container fieldset.mds.bm-box-outline.titled.bm-events-search__outline legend`).first().should("have.css", "margin-left", "-5px");
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__events div.bm-events-search__event div.bm-events-search__boxes div.bm-events-search__details-container fieldset.mds.bm-box-outline.titled.bm-events-search__outline legend`).first().should("have.css", "padding-right", "5px");
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__events div.bm-events-search__event div.bm-events-search__boxes div.bm-events-search__details-container fieldset.mds.bm-box-outline.titled.bm-events-search__outline legend`).first().should("have.css", "margin-right", "-5px");
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__events div.bm-events-search__event div.bm-events-search__boxes div.bm-events-search__details-container fieldset.mds.bm-box-outline.titled.bm-events-search__outline legend`).first().should("have.css", "font-size", "16px");
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__events div.bm-events-search__event div.bm-events-search__boxes div.bm-events-search__details-container fieldset.mds.bm-box-outline.titled.bm-events-search__outline legend`).first().should("have.css", "line-height", "22px");
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__events div.bm-events-search__event div.bm-events-search__boxes div.bm-events-search__details-container fieldset.mds.bm-box-outline.titled.bm-events-search__outline legend`).first().should("have.css", "text-decoration").should("be.oneOf", ["none", `${ColorTextStrong}`, "none solid rgb(46, 46, 46)", "none solid rgb(46, 46, 46)"]);
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__events div.bm-events-search__event div.bm-events-search__boxes div.bm-events-search__details-container fieldset.mds.bm-box-outline.titled.bm-events-search__outline legend`).first().should("have.css", "font-weight", "700");
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__events div.bm-events-search__event div.bm-events-search__boxes div.bm-events-search__details-container fieldset.mds.bm-box-outline.titled.bm-events-search__outline legend`).first().should("have.css", "color", `${ColorTextStrong}`);
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__events div.bm-events-search__event div.bm-events-search__boxes div.bm-events-search__details-container fieldset.mds.bm-box-outline.titled.bm-events-search__outline legend`).first().should("have.css", "width", "99.25px");
    });
    it("Sprawdzenie lewej strony - styli opisów", () => {
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__events div.bm-events-search__event-header label.bm-events-search__accordion-chevron`).first().click();
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__events div.bm-events-search__event div.bm-events-search__boxes div.bm-events-search__details-container fieldset.mds.bm-box-outline.titled.bm-events-search__outline div.bm-events-search__label p`).first().should("have.css", "color", `${ColorGray10}`);
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__events div.bm-events-search__event div.bm-events-search__boxes div.bm-events-search__details-container fieldset.mds.bm-box-outline.titled.bm-events-search__outline div.bm-events-search__label p`).first().should("have.css", "font-weight", "400");
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__events div.bm-events-search__event div.bm-events-search__boxes div.bm-events-search__details-container fieldset.mds.bm-box-outline.titled.bm-events-search__outline div.bm-events-search__label p`).first().should("have.css", "font-size", "16px");
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__events div.bm-events-search__event div.bm-events-search__boxes div.bm-events-search__details-container fieldset.mds.bm-box-outline.titled.bm-events-search__outline div.bm-events-search__label p`).first().should("have.css", "line-height", "22px");
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__events div.bm-events-search__event div.bm-events-search__boxes div.bm-events-search__details-container fieldset.mds.bm-box-outline.titled.bm-events-search__outline div.bm-events-search__label p`).first().should("have.css", "margin-bottom", "8px");
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__events div.bm-events-search__event div.bm-events-search__boxes div.bm-events-search__details-container fieldset.mds.bm-box-outline.titled.bm-events-search__outline div.bm-events-search__label p`).first().should("have.css", "text-decoration").should("be.oneOf", ["none", "rgb(115, 115, 115)", "none solid rgb(115, 115, 115)"]);
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__events div.bm-events-search__event div.bm-events-search__boxes div.bm-events-search__details-container fieldset.mds.bm-box-outline.titled.bm-events-search__outline div.bm-events-search__info-text p`).first().should("have.css", "text-decoration").should("be.oneOf", ["none", "rgb(46, 46, 46)", "none solid rgb(46, 46, 46)"]);
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__events div.bm-events-search__event div.bm-events-search__boxes div.bm-events-search__details-container fieldset.mds.bm-box-outline.titled.bm-events-search__outline div.bm-events-search__info-text p`).first().should("have.css", "color", `${ColorTextStrong}`);
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__events div.bm-events-search__event div.bm-events-search__boxes div.bm-events-search__details-container fieldset.mds.bm-box-outline.titled.bm-events-search__outline div.bm-events-search__info-text p`).first().should("have.css", "font", "700 16px / 22px Roboto");
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__events div.bm-events-search__event div.bm-events-search__boxes div.bm-events-search__details-container fieldset.mds.bm-box-outline.titled.bm-events-search__outline div.bm-events-search__info-text p`).first().should("have.css", "line-height", "22px");
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__events div.bm-events-search__event div.bm-events-search__boxes div.bm-events-search__details-container fieldset.mds.bm-box-outline.titled.bm-events-search__outline div.bm-events-search__info-text p`).first().should("have.css", "letter-spacing", "-0.06px");
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__events div.bm-events-search__event div.bm-events-search__boxes div.bm-events-search__details-container fieldset.mds.bm-box-outline.titled.bm-events-search__outline div.bm-events-search__info-text p`).first().should("have.css", "margin-bottom", "0px");
    });
    it("Sprawdzenie prawej strony - kontener", () => {
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__events div.bm-events-search__event-header label.bm-events-search__accordion-chevron`).first().click();
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__events div.bm-events-search__event div.bm-events-search__boxes div.bm-events-search__address-container`).first().should("have.css", "width", "424px");
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__events div.bm-events-search__event div.bm-events-search__boxes div.bm-events-search__address-container`).first().should("have.css", "margin", "10px 0px 0px 10px");
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__events div.bm-events-search__event div.bm-events-search__boxes div.bm-events-search__address-container`).first().should("have.css", "box-sizing", "border-box");
    });
    it("Sprawdzenie środka kontenera", () => {
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__events div.bm-events-search__event-header label.bm-events-search__accordion-chevron`).first().click();
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__events div.bm-events-search__event div.bm-events-search__boxes div.bm-events-search__address-container div.bm-events-search__address-vertical-container`).first().should("have.css", "height").should((height) => {
            // ensure the unit is in pixels
            expect(height).to.include('px')
            // get Number value and assert "381.15625px"
            expect(parseInt(height, 10)).to.be.within(414, 415);
          });;
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__events div.bm-events-search__event div.bm-events-search__boxes div.bm-events-search__address-container div.bm-events-search__address-vertical-container`).first().should("have.css", "display", "flex");
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__events div.bm-events-search__event div.bm-events-search__boxes div.bm-events-search__address-container div.bm-events-search__address-vertical-container`).first().should("have.css", "flex-direction", "column");
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__events div.bm-events-search__event div.bm-events-search__boxes div.bm-events-search__address-container div.bm-events-search__address-vertical-container`).first().should("have.css", "box-sizing", "border-box");    
    });
    it("Sprawdzenie styli kontenera Firma", () => {
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__events div.bm-events-search__event-header label.bm-events-search__accordion-chevron`).first().click();
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__events div.bm-events-search__event div.bm-events-search__boxes div.bm-events-search__address-container div.bm-events-search__address-vertical-container fieldset.mds.bm-box-outline.titled.bm-events-search__address-outline`).first().should("have.css", "box-sizing", "border-box");
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__events div.bm-events-search__event div.bm-events-search__boxes div.bm-events-search__address-container div.bm-events-search__address-vertical-container fieldset.mds.bm-box-outline.titled.bm-events-search__address-outline`).first().should("have.css", "padding-top", "16px");
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__events div.bm-events-search__event div.bm-events-search__boxes div.bm-events-search__address-container div.bm-events-search__address-vertical-container fieldset.mds.bm-box-outline.titled.bm-events-search__address-outline`).first().should("have.css", "display", "flex");
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__events div.bm-events-search__event div.bm-events-search__boxes div.bm-events-search__address-container div.bm-events-search__address-vertical-container fieldset.mds.bm-box-outline.titled.bm-events-search__address-outline`).first().should("have.css", "flex-direction", "column");
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__events div.bm-events-search__event div.bm-events-search__boxes div.bm-events-search__address-container div.bm-events-search__address-vertical-container fieldset.mds.bm-box-outline.titled.bm-events-search__address-outline`).first().should("have.css", "width").should((weight) => {
            // ensure the unit is in pixels
            expect(weight).to.include('px')
            // get Number value and assert "381.15625px"
            expect(parseInt(weight, 10)).to.be.within(424, 425);
        });
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__events div.bm-events-search__event div.bm-events-search__boxes div.bm-events-search__address-container div.bm-events-search__address-vertical-container fieldset.mds.bm-box-outline.titled.bm-events-search__address-outline`).first().should("have.css", "max-width", "640px");
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__events div.bm-events-search__event div.bm-events-search__boxes div.bm-events-search__address-container div.bm-events-search__address-vertical-container fieldset.mds.bm-box-outline.titled.bm-events-search__address-outline`).first().should("have.css", "padding").should("be.oneOf", ["32px", "16px 32px 32px"]);
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__events div.bm-events-search__event div.bm-events-search__boxes div.bm-events-search__address-container div.bm-events-search__address-vertical-container fieldset.mds.bm-box-outline.titled.bm-events-search__address-outline`).first().should("have.css", "background").should("be.oneOf", ["rgb(255, 255, 255)", "rgb(255, 255, 255) none repeat scroll 0% 0% / auto padding-box border-box"]);
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__events div.bm-events-search__event div.bm-events-search__boxes div.bm-events-search__address-container div.bm-events-search__address-vertical-container fieldset.mds.bm-box-outline.titled.bm-events-search__address-outline`).first().should("have.css", "border").should("be.oneOf", ["1px solid rgb(211, 211, 211)", "1.33333px solid rgb(211, 211, 211)"]);
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__events div.bm-events-search__event div.bm-events-search__boxes div.bm-events-search__address-container div.bm-events-search__address-vertical-container fieldset.mds.bm-box-outline.titled.bm-events-search__address-outline`).first().should("have.css", "border-radius", "10px");
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__events div.bm-events-search__event div.bm-events-search__boxes div.bm-events-search__address-container div.bm-events-search__address-vertical-container fieldset.mds.bm-box-outline.titled.bm-events-search__address-outline`).first().should("have.css", "flex-grow", "1");
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__events div.bm-events-search__event div.bm-events-search__boxes div.bm-events-search__address-container div.bm-events-search__address-vertical-container fieldset.mds.bm-box-outline.titled.bm-events-search__address-outline`).first().should("have.css", "margin-top", "16px");    
    });
    it("Sprawdzenie napisu firma", () => {
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__events div.bm-events-search__event-header label.bm-events-search__accordion-chevron`).first().click();
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__events div.bm-events-search__event div.bm-events-search__boxes div.bm-events-search__address-container div.bm-events-search__address-vertical-container fieldset.mds.bm-box-outline.titled.bm-events-search__address-outline legend`).first().should("have.css", "text-transform", "uppercase");
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__events div.bm-events-search__event div.bm-events-search__boxes div.bm-events-search__address-container div.bm-events-search__address-vertical-container fieldset.mds.bm-box-outline.titled.bm-events-search__address-outline legend`).first().should("have.css", "padding-top", "3px");
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__events div.bm-events-search__event div.bm-events-search__boxes div.bm-events-search__address-container div.bm-events-search__address-vertical-container fieldset.mds.bm-box-outline.titled.bm-events-search__address-outline legend`).first().should("have.css", "padding-left", "5px");
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__events div.bm-events-search__event div.bm-events-search__boxes div.bm-events-search__address-container div.bm-events-search__address-vertical-container fieldset.mds.bm-box-outline.titled.bm-events-search__address-outline legend`).first().should("have.css", "margin-left", "-5px");
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__events div.bm-events-search__event div.bm-events-search__boxes div.bm-events-search__address-container div.bm-events-search__address-vertical-container fieldset.mds.bm-box-outline.titled.bm-events-search__address-outline legend`).first().should("have.css", "padding-right", "5px");
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__events div.bm-events-search__event div.bm-events-search__boxes div.bm-events-search__address-container div.bm-events-search__address-vertical-container fieldset.mds.bm-box-outline.titled.bm-events-search__address-outline legend`).first().should("have.css", "margin-right", "-5px");
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__events div.bm-events-search__event div.bm-events-search__boxes div.bm-events-search__address-container div.bm-events-search__address-vertical-container fieldset.mds.bm-box-outline.titled.bm-events-search__address-outline legend`).first().should("have.css", "font-size", "16px");
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__events div.bm-events-search__event div.bm-events-search__boxes div.bm-events-search__address-container div.bm-events-search__address-vertical-container fieldset.mds.bm-box-outline.titled.bm-events-search__address-outline legend`).first().should("have.css", "line-height", "22px");
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__events div.bm-events-search__event div.bm-events-search__boxes div.bm-events-search__address-container div.bm-events-search__address-vertical-container fieldset.mds.bm-box-outline.titled.bm-events-search__address-outline legend`).first().should("have.css", "text-decoration").should("be.oneOf", ["none", `${ColorTextStrong}`, "none solid rgb(46, 46, 46)", "none solid rgb(46, 46, 46)"]);
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__events div.bm-events-search__event div.bm-events-search__boxes div.bm-events-search__address-container div.bm-events-search__address-vertical-container fieldset.mds.bm-box-outline.titled.bm-events-search__address-outline legend`).first().should("have.css", "font-weight", "700");
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__events div.bm-events-search__event div.bm-events-search__boxes div.bm-events-search__address-container div.bm-events-search__address-vertical-container fieldset.mds.bm-box-outline.titled.bm-events-search__address-outline legend`).first().should("have.css", "color", `${ColorTextStrong}`);
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__events div.bm-events-search__event div.bm-events-search__boxes div.bm-events-search__address-container div.bm-events-search__address-vertical-container fieldset.mds.bm-box-outline.titled.bm-events-search__address-outline legend`).first().should("have.css", "width").should((height) => {
            // ensure the unit is in pixels
            expect(height).to.include('px')
            // get Number value and assert "381.15625px"
            expect(parseInt(height, 10)).to.be.within(58, 59);
        });
    });
    it("Sprawdzenie aktualności danych", () => {
        let date = new Date();
        let today = date.getDate();
        let month = date.getMonth() + 1;
        let year = date.getFullYear();
        let yesterday = today - 1;
        let dayBeforeYesterday = today - 2;
        let dayBeforeBeforeYesterday = today - 3;
        let dayBeforeBeforeBeforeYesterday = today - 4;

        let todayDate = `${today}.${month}.${year}`;
        let yesterdayDate = `${yesterday}.${month}.${year}`;
        let dayBeforeYesterdayDate = `${dayBeforeYesterday}.${month}.${year}`;
        let dayBeforeBeforeYesterdayDate = `${dayBeforeBeforeYesterday}.${month}.${year}`;
        let dayBeforeBeforeBeforeYesterdayDate = `${dayBeforeBeforeBeforeYesterday}.${month}.${year}`;

        console.log(todayDate);
        console.log(yesterdayDate);
        console.log(dayBeforeYesterdayDate);
        console.log(dayBeforeBeforeYesterdayDate);
        console.log(dayBeforeBeforeBeforeYesterdayDate);
        cy.get(`${shareholdersSearchId} div.mds.bm-events-search div.bm-events-search__container div.bm-events-search__events div.bm-events-search__event-header label.bm-events-search__event-header-container div.bm-events-search__event-title-date`).first().should("eq").should("be.oneOf", [``, ``, ``, ``,])
    })
    

})